<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Version>0.3.0</Version>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
